# Generated by Django 2.2.5 on 2020-11-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201102_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='convalidationGranted',
            field=models.BooleanField(default=False),
        ),
    ]
