# Generated by Django 2.2.5 on 2020-11-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201102_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theorygroup',
            options={},
        ),
    ]
