# Generated by Django 2.2.5 on 2020-11-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201102_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupconstraints',
            options={'ordering': ('labGroup', 'theoryGroup')},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('first_name', 'last_name')},
        ),
        migrations.AlterModelOptions(
            name='theorygroup',
            options={'ordering': ('groupName',)},
        ),
    ]
