# Generated by Django 2.2.5 on 2020-11-16 16:57

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201116_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': (django.db.models.functions.text.Upper('last_name'), 'first_name')},
        ),
    ]
