# Generated by Django 2.2.5 on 2020-11-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201102_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='student1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Student'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='student2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Student'),
        ),
    ]
