# Generated by Django 2.2.5 on 2020-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201108_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherconstraints',
            name='minGradeLabConv',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='otherconstraints',
            name='minGradeTheoryConv',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
        ),
    ]
