# Generated by Django 2.2.5 on 2020-11-16 16:43

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201108_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': (django.db.models.functions.text.Upper('last_name'), 'first_name')},
        ),
        migrations.AlterField(
            model_name='pair',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
