# Generated by Django 2.2.5 on 2020-10-05 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20201004_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 16, 5, 40, 360695, tzinfo=utc)),
        ),
    ]
